export const HOTKEYS = {
  backToLanding: 'Shift+Escape',
  cancelEditing: 'Escape',
  drawTool: 'D',
  eraseTool: 'E',
  fillEraseTool: 'Shift+E',
  fillTool: 'Shift+D',
  exportGlb: 'Mod+E',
  isometricCamera: 'I',
  newPiece: 'N',
  paintTool: 'P',
  paintFillTool: 'Shift+P',
  perspectiveCamera: 'O',
  pushOrDonePiece: 'Mod+Enter',
  redo: 'Mod+Shift+Z',
  saveProject: 'Mod+S',
  undo: 'Mod+Z',
  viewFront: 'F',
  viewSide: 'R',
  viewTop: 'T'
} as const;
